const levelsArr = [
    {
        id: "0",
        value: "5, 10",
        target: "50",
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
        calculateScore: "0",
    },
    {
        id: "1",
        value: "2, 3, 5",
        target: "10",
        createFixCub: [
            {
                fixCubCard: "47",
                fixCubValue: "",
            },
        ],
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
        calculateScore: "0",
    },
    {
        id: "2",
        value: "1, 4, 5, 10, ✘",
        target: "20",
        startTimerGame: "0",
        getRandomValue: "1",
        gameProcess: "1",
        calculateScore: "0",
    },
    {
        id: "3",
        value: "2, 3, 5, 10",
        target: "30",
        startTimerGame: "0",
        getRandomValue: "7",
        gameProcess: "1",
        calculateScore: "1",
    },
    {
        id: "4",
        value: "1, 2, 5, 10",
        target: "30",
        startTimerGame: "0",
        getRandomValue: "4",
        gameProcess: "4",
        gameProcessSwap: "10",
        calculateScore: "0",
    },
    {
        id: "5",
        value: "3, 4, 5, 10",
        target: "30",
        startTimerGame: "0",
        getRandomValue: "5",
        gameProcess: "5",
        gameProcessDel: "10",
        calculateScore: "0",
    },
    {
        id: "6",
        value: "2, 3, 10",
        target: "40",
        createFixCub: [
            {
                fixCubCard: "28",
                fixCubValue: "20",
            },
        ],
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
        calculateScore: "0",
    },
    {
        id: "7",
        value: "2, 4, 5, 10, ⇆ ",
        target: "40",
        startTimerGame: "0",
        getRandomValue: "2",
        gameProcess: "2",
        calculateScore: "0",
    },
    {
        id: "8",
        value: "1, 4, 10",
        target: "50",
        createSingleCub: [
            {
                singleCubCard: "8",
                singleCubValue: "50",
            },
        ],
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
        calculateScore: "0",
    },
    {
        id: "9",
        value: "0, 2, 3, 4, 5, 10",
        target: "50",
        startTimerGame: "0",
        getRandomValue: "6",
        gameProcess: "0",
        calculateScore: "2",
    },
    {
        id: "10",
        value: "2, 4, 6, 10, ⤋",
        target: "50",
        startTimerGame: "0",
        getRandomValue: "3",
        gameProcess: "3",
        calculateScore: "0",
    },
    {
        id: "11",
        value: "4, 5, 6",
        target: "20",
        createFixCub: [
            {
                fixCubCard: "8",
                fixCubValue: "",
            },
            {
                fixCubCard: "48",
                fixCubValue: "",
            },
        ],
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
        calculateScore: "0",
    },
    {
        id: "12",
        value: "4, 5, 6, 10, ✘",
        target: "30",
        startTimerGame: "0",
        getRandomValue: "1",
        gameProcess: "1",
        calculateScore: "0",
    },
    {
        id: "13",
        value: "3, 5, 7, 10",
        target: "30",
        startTimerGame: "0",
        getRandomValue: "7",
        gameProcess: "1",
        calculateScore: "1",
    },
    {
        id: "14",
        value: "3, 5, 6, 10",
        target: "40",
        startTimerGame: "0",
        getRandomValue: "4",
        gameProcess: "4",
        gameProcessSwap: "15",
        calculateScore: "0",
    },
    {
        id: "15",
        value: "4, 5, 7, 10",
        target: "40",
        startTimerGame: "0",
        getRandomValue: "5",
        gameProcess: "5",
        gameProcessDel: "15",
        calculateScore: "0",
    },
    {
        id: "16",
        value: "3, 7, 10",
        target: "50",
        createFixCub: [
            {
                fixCubCard: "7",
                fixCubValue: "25",
            },
            {
                fixCubCard: "47",
                fixCubValue: "25",
            },
        ],
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
        calculateScore: "0",
    },
    {
        id: "17",
        value: "5, 6, 7, 10, ⇆ ",
        target: "50",
        startTimerGame: "0",
        getRandomValue: "2",
        gameProcess: "2",
        calculateScore: "0",
    },
    {
        id: "18",
        value: "4, 6, 10",
        target: "60",
        createSingleCub: [
            {
                singleCubCard: "7",
                singleCubValue: "30",
            },
            {
                singleCubCard: "48",
                singleCubValue: "30",
            },
        ],
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
        calculateScore: "0",
    },
    {
        id: "19",
        value: "0, 3, 5, 6, 10",
        target: "60",
        startTimerGame: "0",
        getRandomValue: "6",
        gameProcess: "0",
        calculateScore: "2",
    },
    {
        id: "20",
        value: "4, 5, 6, 7, 10, ⤋",
        target: "70",
        startTimerGame: "0",
        getRandomValue: "3",
        gameProcess: "3",
        calculateScore: "0",
    },
    {
        id: "21",
        value: "5, 7, 8",
        target: "30",
        createFixCub: [
            {
                fixCubCard: "7",
                fixCubValue: "",
            },
            {
                fixCubCard: "27",
                fixCubValue: "",
            },
            {
                fixCubCard: "47",
                fixCubValue: "",
            },
        ],
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
        calculateScore: "0",
    },
    {
        id: "22",
        value: "5, 6, 9, 10, ✘",
        target: "40",
        startTimerGame: "0",
        getRandomValue: "1",
        gameProcess: "1",
        calculateScore: "0",
    },
    {
        id: "23",
        value: "5, 7, 8, 10",
        target: "40",
        startTimerGame: "0",
        getRandomValue: "7",
        gameProcess: "1",
        calculateScore: "1",
    },
    {
        id: "24",
        value: "5, 6, 7, 10",
        target: "50",
        startTimerGame: "0",
        getRandomValue: "4",
        gameProcess: "4",
        gameProcessSwap: "20",
        calculateScore: "0",
    },
    {
        id: "25",
        value: "5, 7, 9, 10",
        target: "50",
        startTimerGame: "0",
        getRandomValue: "5",
        gameProcess: "5",
        gameProcessDel: "20",
        calculateScore: "0",
    },
    {
        id: "26",
        value: "7, 8, 10",
        target: "60",
        createFixCub: [
            {
                fixCubCard: "6",
                fixCubValue: "30",
            },
            {
                fixCubCard: "27",
                fixCubValue: "30",
            },
            {
                fixCubCard: "48",
                fixCubValue: "30",
            },
        ],
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
        calculateScore: "0",
    },
    {
        id: "27",
        value: "5, 8, 9, 10, ⇆ ",
        target: "70",
        startTimerGame: "0",
        getRandomValue: "2",
        gameProcess: "2",
        calculateScore: "0",
    },
    {
        id: "28",
        value: "6, 9, 10",
        target: "80",
        createSingleCub: [
            {
                singleCubCard: "29",
                singleCubValue: "30",
            },
            {
                singleCubCard: "28",
                singleCubValue: "30",
            },
            {
                singleCubCard: "27",
                singleCubValue: "30",
            },
        ],
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
        calculateScore: "0",
    },
    {
        id: "29",
        value: "0, 5, 8, 9, 10",
        target: "90",
        startTimerGame: "0",
        getRandomValue: "6",
        gameProcess: "0",
        calculateScore: "2",
    },
    {
        id: "30",
        value: "5, 7, 8, 9, 10, ⤋",
        target: "90",
        startTimerGame: "0",
        getRandomValue: "3",
        gameProcess: "3",
        calculateScore: "0",
    },
    {
        id: "31",
    },
    {
        id: "32",
    },
    {
        id: "33",
    },
    {
        id: "34",
    },
    {
        id: "35",
    },
    {
        id: "36",
    },
    {
        id: "37",
    },
    {
        id: "38",
    },
    {
        id: "39",
    },
    {
        id: "40",
    },

    {
        id: "101",
        value: "2, 3, 5",
        target: "10",
        createFixCub: [
            {
                fixCubCard: "1",
                fixCubValue: "55",
            },
            {
                fixCubCard: "9",
                fixCubValue: "20",
            },
        ],
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
        calculateScore: "0",
    },
];
