const levelsArr = [
    {
        id: "0",
        value: "5, 10",
        target: "50",
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
        calculateScore: "0",
    },
    {
        id: "1",
        value: "2, 3, 5",
        target: "100",
        createFixCub: [
            {
                fixCubCard: "1",
                fixCubValue: "55",
            },
            {
                fixCubCard: "9",
                fixCubValue: "20",
            },
        ],
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
        calculateScore: "0",
    },
    {
        id: "2",
        value: "1, 4, 5, 10, ✘",
        target: "200",
        startTimerGame: "0",
        getRandomValue: "1",
        gameProcess: "1",
        calculateScore: "0",
    },
    {
        id: "3",
        value: "2, 3, 5, 10",
        target: "200",
        startTimerGame: "0",
        getRandomValue: "7",
        gameProcess: "1",
        calculateScore: "1",
    },
    {
        id: "4",
        value: "1, 2, 5, 10",
        target: "300",
        startTimerGame: "0",
        getRandomValue: "4",
        gameProcess: "4",
        gameProcessSwap: "15",
        calculateScore: "0",
    },
    {
        id: "5",
        value: "3, 4, 5, 10",
        target: "300",
        startTimerGame: "0",
        getRandomValue: "5",
        gameProcess: "5",
        gameProcessDel: "25",
        calculateScore: "0",
    },
    {
        id: "6",
        value: "2, 3, 10",
        target: "400",
        createSingleCub: [
            {
                singleCubCard: "9",
                singleCubValue: "55",
            },
        ],
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
        calculateScore: "0",
    },
    {
        id: "7",
        value: "2, 4, 5, 10, ⇆ ",
        target: "400",
        startTimerGame: "0",
        getRandomValue: "2",
        gameProcess: "2",
        calculateScore: "0",
    },
    {
        id: "8",
        value: "1, 4, 10",
        target: "500",
        createSingleCub: [
            {
                singleCubCard: "8",
                singleCubValue: "45",
            },
            {
                singleCubCard: "48",
                singleCubValue: "35",
            },
        ],
        startTimerGame: "0",
        getRandomValue: "0",
        gameProcess: "0",
    },
    {
        id: "9",
        value: "0, 2, 3, 4, 5, 10",
        target: "500",
        startTimerGame: "0",
        getRandomValue: "6",
        gameProcess: "0",
        calculateScore: "2",
    },
    {
        id: "10",
        value: "2, 4, 6, 10, ⤋",
        target: "500",
        startTimerGame: "0",
        getRandomValue: "3",
        gameProcess: "3",
        calculateScore: "0",
    },
];
